//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.7.0
//     from Assets/InputActions.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @InputActions: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @InputActions()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""InputActions"",
    ""maps"": [
        {
            ""name"": ""Player"",
            ""id"": ""32bd98b0-67a6-4510-9481-b61d4fbdde7a"",
            ""actions"": [
                {
                    ""name"": ""AButton"",
                    ""type"": ""Button"",
                    ""id"": ""6e6c868d-dc20-4774-be9c-e912e84797a1"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""PrimaryDirectionalAxis"",
                    ""type"": ""Value"",
                    ""id"": ""3d39919a-d2ef-4c7f-b1fb-3aae880cb095"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""SecondaryDirectionalAxis"",
                    ""type"": ""Value"",
                    ""id"": ""f2ee8e37-c65d-4f73-bbc8-1c9dff3845e3"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""BButton"",
                    ""type"": ""Button"",
                    ""id"": ""2eede954-1d16-4a2d-aaf2-f6a1fa252be3"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ZTarget"",
                    ""type"": ""Button"",
                    ""id"": ""5c6729fd-dba3-4e0c-8dce-1678cded7f6f"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""InteractButton"",
                    ""type"": ""Button"",
                    ""id"": ""836d12ad-fa09-4d85-80ad-dd15a9ec03e9"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""DodgeButton"",
                    ""type"": ""Button"",
                    ""id"": ""32a31865-25f7-49c6-b3b3-35cb28a642c8"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""SwapButton"",
                    ""type"": ""Button"",
                    ""id"": ""7b83b031-42d0-4bfa-bb46-61a3a53e9985"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""c3d7e536-1409-4253-b2fb-ffed6412be8e"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""KBM"",
                    ""action"": ""AButton"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""f9441630-16bb-4deb-b7de-fc44bb7a4f10"",
                    ""path"": ""<Gamepad>/buttonSouth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""AButton"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""2D Vector"",
                    ""id"": ""2c10d76d-aed6-4fb4-ac76-43ba0e3310e8"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PrimaryDirectionalAxis"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""6221f580-533c-46fb-90bc-27c56e094195"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""KBM"",
                    ""action"": ""PrimaryDirectionalAxis"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""a8dd4f4b-f15b-49c9-8d9b-d65d15e18ff5"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""KBM"",
                    ""action"": ""PrimaryDirectionalAxis"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""c3465d5d-67cd-4385-9528-178966fa92f4"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""KBM"",
                    ""action"": ""PrimaryDirectionalAxis"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""f6671042-b736-4fc5-bd79-eb14ba70d0f5"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""KBM"",
                    ""action"": ""PrimaryDirectionalAxis"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""85e233dd-82b0-4489-9f37-60c737f5d9d2"",
                    ""path"": ""<Gamepad>/leftStick"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""PrimaryDirectionalAxis"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""2D Vector"",
                    ""id"": ""5841e2cc-ac3b-4011-b0b7-c3fa2899c0e6"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SecondaryDirectionalAxis"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""c39acdca-3e11-42d3-9728-a028365ee1e4"",
                    ""path"": ""<Keyboard>/upArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""KBM"",
                    ""action"": ""SecondaryDirectionalAxis"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""1dc3440d-cd68-403f-8332-5db1fe30a9a9"",
                    ""path"": ""<Keyboard>/downArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""KBM"",
                    ""action"": ""SecondaryDirectionalAxis"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""2819a615-6524-401b-8370-215d50b772d0"",
                    ""path"": ""<Keyboard>/leftArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""KBM"",
                    ""action"": ""SecondaryDirectionalAxis"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""3038c05c-002f-466d-836f-5c1946a906ea"",
                    ""path"": ""<Keyboard>/rightArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""KBM"",
                    ""action"": ""SecondaryDirectionalAxis"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""24fab239-b9db-47be-8a1c-82e81005d157"",
                    ""path"": ""<Gamepad>/rightStick"",
                    ""interactions"": """",
                    ""processors"": ""ScaleVector2(y=-1)"",
                    ""groups"": ""Gamepad"",
                    ""action"": ""SecondaryDirectionalAxis"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""40ed3f08-f566-4923-a354-1c1ab90f684b"",
                    ""path"": ""<Mouse>/delta"",
                    ""interactions"": """",
                    ""processors"": ""ScaleVector2(x=0.2,y=-0.2)"",
                    ""groups"": ""KBM"",
                    ""action"": ""SecondaryDirectionalAxis"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""44e50099-0391-455a-828e-bc6c7de91104"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""KBM"",
                    ""action"": ""BButton"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""4e5a1303-83c4-46d5-b5ff-41c8414ff042"",
                    ""path"": ""<Gamepad>/buttonEast"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""BButton"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""6c06bc62-b2e9-422a-baf1-30f777d75d29"",
                    ""path"": ""<Keyboard>/leftShift"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""KBM"",
                    ""action"": ""ZTarget"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""bcb2bd17-730a-471f-8305-9383a442ef9c"",
                    ""path"": ""<Gamepad>/leftTrigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""ZTarget"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""d977cf0e-6542-43a7-aac8-98cb67621a55"",
                    ""path"": ""<Keyboard>/e"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""KBM"",
                    ""action"": ""InteractButton"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""fee00090-943e-49c5-b9c2-68219ccb13b7"",
                    ""path"": ""<Gamepad>/buttonWest"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""InteractButton"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""2754e34b-4d9f-4912-a81d-1c7a66866912"",
                    ""path"": ""<Mouse>/rightButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""KBM"",
                    ""action"": ""DodgeButton"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""c60454a5-6bf8-482e-8376-cd95b8d28314"",
                    ""path"": ""<Gamepad>/buttonNorth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""DodgeButton"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""19bf3f1f-6191-4e62-b748-d9cdb662de55"",
                    ""path"": ""<Mouse>/middleButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""KBM"",
                    ""action"": ""SwapButton"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""3b50a44a-9dc3-4ce1-aa4c-5b00305f72aa"",
                    ""path"": ""<Gamepad>/dpad/right"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""SwapButton"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": [
        {
            ""name"": ""KBM"",
            ""bindingGroup"": ""KBM"",
            ""devices"": [
                {
                    ""devicePath"": ""<Keyboard>"",
                    ""isOptional"": false,
                    ""isOR"": false
                }
            ]
        },
        {
            ""name"": ""Gamepad"",
            ""bindingGroup"": ""Gamepad"",
            ""devices"": [
                {
                    ""devicePath"": ""<Gamepad>"",
                    ""isOptional"": false,
                    ""isOR"": false
                }
            ]
        }
    ]
}");
        // Player
        m_Player = asset.FindActionMap("Player", throwIfNotFound: true);
        m_Player_AButton = m_Player.FindAction("AButton", throwIfNotFound: true);
        m_Player_PrimaryDirectionalAxis = m_Player.FindAction("PrimaryDirectionalAxis", throwIfNotFound: true);
        m_Player_SecondaryDirectionalAxis = m_Player.FindAction("SecondaryDirectionalAxis", throwIfNotFound: true);
        m_Player_BButton = m_Player.FindAction("BButton", throwIfNotFound: true);
        m_Player_ZTarget = m_Player.FindAction("ZTarget", throwIfNotFound: true);
        m_Player_InteractButton = m_Player.FindAction("InteractButton", throwIfNotFound: true);
        m_Player_DodgeButton = m_Player.FindAction("DodgeButton", throwIfNotFound: true);
        m_Player_SwapButton = m_Player.FindAction("SwapButton", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Player
    private readonly InputActionMap m_Player;
    private List<IPlayerActions> m_PlayerActionsCallbackInterfaces = new List<IPlayerActions>();
    private readonly InputAction m_Player_AButton;
    private readonly InputAction m_Player_PrimaryDirectionalAxis;
    private readonly InputAction m_Player_SecondaryDirectionalAxis;
    private readonly InputAction m_Player_BButton;
    private readonly InputAction m_Player_ZTarget;
    private readonly InputAction m_Player_InteractButton;
    private readonly InputAction m_Player_DodgeButton;
    private readonly InputAction m_Player_SwapButton;
    public struct PlayerActions
    {
        private @InputActions m_Wrapper;
        public PlayerActions(@InputActions wrapper) { m_Wrapper = wrapper; }
        public InputAction @AButton => m_Wrapper.m_Player_AButton;
        public InputAction @PrimaryDirectionalAxis => m_Wrapper.m_Player_PrimaryDirectionalAxis;
        public InputAction @SecondaryDirectionalAxis => m_Wrapper.m_Player_SecondaryDirectionalAxis;
        public InputAction @BButton => m_Wrapper.m_Player_BButton;
        public InputAction @ZTarget => m_Wrapper.m_Player_ZTarget;
        public InputAction @InteractButton => m_Wrapper.m_Player_InteractButton;
        public InputAction @DodgeButton => m_Wrapper.m_Player_DodgeButton;
        public InputAction @SwapButton => m_Wrapper.m_Player_SwapButton;
        public InputActionMap Get() { return m_Wrapper.m_Player; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(PlayerActions set) { return set.Get(); }
        public void AddCallbacks(IPlayerActions instance)
        {
            if (instance == null || m_Wrapper.m_PlayerActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_PlayerActionsCallbackInterfaces.Add(instance);
            @AButton.started += instance.OnAButton;
            @AButton.performed += instance.OnAButton;
            @AButton.canceled += instance.OnAButton;
            @PrimaryDirectionalAxis.started += instance.OnPrimaryDirectionalAxis;
            @PrimaryDirectionalAxis.performed += instance.OnPrimaryDirectionalAxis;
            @PrimaryDirectionalAxis.canceled += instance.OnPrimaryDirectionalAxis;
            @SecondaryDirectionalAxis.started += instance.OnSecondaryDirectionalAxis;
            @SecondaryDirectionalAxis.performed += instance.OnSecondaryDirectionalAxis;
            @SecondaryDirectionalAxis.canceled += instance.OnSecondaryDirectionalAxis;
            @BButton.started += instance.OnBButton;
            @BButton.performed += instance.OnBButton;
            @BButton.canceled += instance.OnBButton;
            @ZTarget.started += instance.OnZTarget;
            @ZTarget.performed += instance.OnZTarget;
            @ZTarget.canceled += instance.OnZTarget;
            @InteractButton.started += instance.OnInteractButton;
            @InteractButton.performed += instance.OnInteractButton;
            @InteractButton.canceled += instance.OnInteractButton;
            @DodgeButton.started += instance.OnDodgeButton;
            @DodgeButton.performed += instance.OnDodgeButton;
            @DodgeButton.canceled += instance.OnDodgeButton;
            @SwapButton.started += instance.OnSwapButton;
            @SwapButton.performed += instance.OnSwapButton;
            @SwapButton.canceled += instance.OnSwapButton;
        }

        private void UnregisterCallbacks(IPlayerActions instance)
        {
            @AButton.started -= instance.OnAButton;
            @AButton.performed -= instance.OnAButton;
            @AButton.canceled -= instance.OnAButton;
            @PrimaryDirectionalAxis.started -= instance.OnPrimaryDirectionalAxis;
            @PrimaryDirectionalAxis.performed -= instance.OnPrimaryDirectionalAxis;
            @PrimaryDirectionalAxis.canceled -= instance.OnPrimaryDirectionalAxis;
            @SecondaryDirectionalAxis.started -= instance.OnSecondaryDirectionalAxis;
            @SecondaryDirectionalAxis.performed -= instance.OnSecondaryDirectionalAxis;
            @SecondaryDirectionalAxis.canceled -= instance.OnSecondaryDirectionalAxis;
            @BButton.started -= instance.OnBButton;
            @BButton.performed -= instance.OnBButton;
            @BButton.canceled -= instance.OnBButton;
            @ZTarget.started -= instance.OnZTarget;
            @ZTarget.performed -= instance.OnZTarget;
            @ZTarget.canceled -= instance.OnZTarget;
            @InteractButton.started -= instance.OnInteractButton;
            @InteractButton.performed -= instance.OnInteractButton;
            @InteractButton.canceled -= instance.OnInteractButton;
            @DodgeButton.started -= instance.OnDodgeButton;
            @DodgeButton.performed -= instance.OnDodgeButton;
            @DodgeButton.canceled -= instance.OnDodgeButton;
            @SwapButton.started -= instance.OnSwapButton;
            @SwapButton.performed -= instance.OnSwapButton;
            @SwapButton.canceled -= instance.OnSwapButton;
        }

        public void RemoveCallbacks(IPlayerActions instance)
        {
            if (m_Wrapper.m_PlayerActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IPlayerActions instance)
        {
            foreach (var item in m_Wrapper.m_PlayerActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_PlayerActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public PlayerActions @Player => new PlayerActions(this);
    private int m_KBMSchemeIndex = -1;
    public InputControlScheme KBMScheme
    {
        get
        {
            if (m_KBMSchemeIndex == -1) m_KBMSchemeIndex = asset.FindControlSchemeIndex("KBM");
            return asset.controlSchemes[m_KBMSchemeIndex];
        }
    }
    private int m_GamepadSchemeIndex = -1;
    public InputControlScheme GamepadScheme
    {
        get
        {
            if (m_GamepadSchemeIndex == -1) m_GamepadSchemeIndex = asset.FindControlSchemeIndex("Gamepad");
            return asset.controlSchemes[m_GamepadSchemeIndex];
        }
    }
    public interface IPlayerActions
    {
        void OnAButton(InputAction.CallbackContext context);
        void OnPrimaryDirectionalAxis(InputAction.CallbackContext context);
        void OnSecondaryDirectionalAxis(InputAction.CallbackContext context);
        void OnBButton(InputAction.CallbackContext context);
        void OnZTarget(InputAction.CallbackContext context);
        void OnInteractButton(InputAction.CallbackContext context);
        void OnDodgeButton(InputAction.CallbackContext context);
        void OnSwapButton(InputAction.CallbackContext context);
    }
}
